export default {
    ts: "TypeScript",
    js: "JavaScript",
    python: "Python",
    mysql: "MySQL",
    mongodb: "MongoDB",
    postgresql: "PostgreSQL",
    starrocks: "StarRocks",
    clickhouse: "ClickHouse",
    figma: "Figma",
    tailwindcss: "TailwindCSS",
    "next.js": "Next.js",
    "react.js": "React.js",
    "redux.js": "Redux.js",
    "vue.js": "Vue.js",
    svelte: "Svelte",
    "react native": "React Native",
    expo: "Expo",
    "google cloud": "Google Cloud",
    "github actions": "GitHub Actions",
    jest: "Jest",
    express: "Express",
    github: "GitHub",
    gulp: "Gulp",
    flask: "Flask",
    quart: "Quart",
    webpack: "Webpack"
}
